name:                hs-trillian
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/hs-trillian#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2019 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - proto-lens
  - proto-lens-runtime

executables:
  hs-trillian:
    source-dirs:      src
    main:             Main.hs
