resolver: lts-13.29

packages:
- ./hs-trillian-log
- ./hs-trillian-protos
- ./hs-trillian-examples

extra-deps:
  - http2-client-0.9.0.0
  - http2-grpc-types-0.4.0.0
  - lens-labels-0.3.0.1
  - proto-lens-0.5.0.0
  - proto-lens-protoc-0.5.0.0
  - proto-lens-runtime-0.5.0.0
  - proto-lens-setup-0.4.0.2
  - git: https://github.com/lucasdicioccio/http2-client-grpc
    commit: 6a1aacfc18e312ef57552133f13dd1024c178706

explicit-setup-deps:
  hs-trillian: true
