name:                hs-trillian-examples
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/hs-trillian#readme
license:             Apache
author:              Martin Allen
maintainer:          martin@foam.space
copyright:           2019 Martin Allen
category:            Web

custom-setup:
  dependencies:
    - base
    - Cabal
    - proto-lens-setup

dependencies:
  - base >= 4.7 && < 5
  - proto-lens
  - proto-lens-runtime
  - http2-client
  - http2-client-grpc
  - hs-trillian-log
  - hs-trillian-protos


default-extensions:
- DataKinds

executables:
  eth-slurper:
    source-dirs: eth-slurp
    main: Main.hs
    ghc-options:
    - -Werror
    - -Wall
    dependencies:
    - errors
