name:                hs-trillian-examples
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/hs-trillian#readme
license:             Apache
author:              Martin Allen
maintainer:          martin@foam.space
copyright:           2019 Martin Allen
category:            Web

dependencies:
  - base >= 4.7 && < 5
  - proto-lens
  - proto-lens-runtime
  - http2-client
  - http2-client-grpc
  - hs-trillian-log
  - hs-trillian-protos

library:
  source-dirs: src
  ghc-options:
  - -Werror
  - -Wall
  dependencies:
  - errors
  - transformers


default-extensions:
- LambdaCase

executables:
  ethslurp:
    source-dirs: ethslurp
    main: Main.hs
    ghc-options:
    - -Werror
    - -Wall
  simple-storage:
    source-dirs: simple-storage
    main: Main.hs
    ghc-options:
    - -Werror
    - -Wall
