name:                hs-trillian-admin
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/hs-trillian#readme
license:             Apache
author:              Martin Allen
maintainer:          martin@foam.space
copyright:           2019 Martin Allen
category:            Web


dependencies:
  - base >= 4.7 && < 5
  - hs-trillian-protos
  - http2-client
  - http2-client-grpc

default-extensions:
 - DataKinds

library:
  source-dirs: src
  ghc-options:
  - -Werror
  - -Wall
  exposed-modules:
  - Trillian.Admin.RPCCall
