name:                hs-trillian-protos
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/hs-trillian#readme
license:             Apache
author:              Author name here
maintainer:          martin@foam.space
copyright:           2019 Martin Allen
category:            Web
extra-source-files:
- protos/**/*.proto

custom-setup:
  dependencies:
    - base
    - Cabal
    - proto-lens-setup

dependencies:
  - base >= 4.7 && < 5
  - proto-lens
  - proto-lens-runtime

library:
  source-dirs: src
  exposed-modules:
  - Proto.Trillian
  - Proto.Trillian_Fields
  - Proto.TrillianLogApi
  - Proto.TrillianLogApi_Fields
  - Proto.TrillianAdminApi
  - Proto.TrillianAdminApi_Fields
  - Proto.Google.Api.Annotations
  - Proto.Google.Api.Annotations_Fields
  - Proto.Google.Api.Http
  - Proto.Google.Api.Http_Fields
  - Proto.Google.Protobuf.Any
  - Proto.Google.Protobuf.Any_Fields
  - Proto.Google.Protobuf.Duration
  - Proto.Google.Protobuf.Duration_Fields
  - Proto.Google.Protobuf.FieldMask
  - Proto.Google.Protobuf.FieldMask_Fields
  - Proto.Google.Protobuf.Timestamp
  - Proto.Google.Protobuf.Timestamp_Fields
  - Proto.Google.Rpc.Status
  - Proto.Google.Rpc.Status_Fields
  - Proto.Crypto.Keyspb.Keyspb
  - Proto.Crypto.Keyspb.Keyspb_Fields
  - Proto.Crypto.Sigpb.Sigpb
  - Proto.Crypto.Sigpb.Sigpb_Fields
